import { z } from 'zod';

import { GENDERS } from '@shared/enums';
import { paginationQuerySchema, uuidSchema } from '@shared/schemas/common';
import { signedMoneySchema } from '@shared/schemas/money';
import { phoneSchema } from '@shared/schemas/users';

/** `:patientId` route parameter of every patient-nested route. */
export const patientIdParamSchema = z.object({ patientId: uuidSchema });
export type PatientIdParam = z.infer<typeof patientIdParamSchema>;

/** Gregorian, `YYYY-MM-DD` — a date of birth has no time or zone. */
export const dateOnlySchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, 'Expected a YYYY-MM-DD date')
  .refine((value) => !Number.isNaN(Date.parse(`${value}T00:00:00Z`)), 'Not a valid date');

/**
 * Everything on the patient file.
 *
 * ROLES.md calls this `PatientClinicalView` — admin and doctor only. It is the
 * full row minus nothing, because no field here is more sensitive than the
 * record's existence; the clinical detail lives in the related tables.
 */
export const patientClinicalViewSchema = z.object({
  id: z.uuid(),
  clinicId: z.uuid(),
  /** Per-clinic sequential file number, generated by the API. */
  fileNumber: z.string(),
  fullName: z.string(),
  phone: z.string(),
  dateOfBirth: dateOnlySchema.nullable(),
  gender: z.enum(GENDERS).nullable(),
  address: z.string().nullable(),
  nationalId: z.string().nullable(),
  emergencyContactName: z.string().nullable(),
  emergencyContactPhone: z.string().nullable(),
  notes: z.string().nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  /** sum(charges) − sum(payments), computed on read and never stored. */
  balance: signedMoneySchema.optional(),
});
export type PatientClinicalView = z.infer<typeof patientClinicalViewSchema>;

/**
 * ROLES.md `PatientPublicView` — what a receptionist or technician receives.
 *
 * `balance` is present for a receptionist and absent for a technician: the
 * matrix lists the field on this view, but the field rules say a technician
 * response must never include financial patient data, and the narrower rule
 * wins. It is computed from the ledgers on every read and stored nowhere
 * (CLAUDE.md: never store a balance).
 */
export const patientPublicViewSchema = patientClinicalViewSchema
  .pick({
    id: true,
    fileNumber: true,
    fullName: true,
    phone: true,
    dateOfBirth: true,
  })
  .extend({ balance: signedMoneySchema.optional() });
export type PatientPublicView = z.infer<typeof patientPublicViewSchema>;

/** Either shape, depending on the caller's role. */
export const patientViewSchema = z.union([patientClinicalViewSchema, patientPublicViewSchema]);
export type PatientView = PatientClinicalView | PatientPublicView;

const patientWritableFields = {
  fullName: z.string().trim().min(2).max(160),
  phone: phoneSchema,
  dateOfBirth: dateOnlySchema.nullish(),
  gender: z.enum(GENDERS).nullish(),
  address: z.string().trim().max(500).nullish(),
  nationalId: z.string().trim().max(64).nullish(),
  emergencyContactName: z.string().trim().max(160).nullish(),
  emergencyContactPhone: phoneSchema.nullish(),
  notes: z.string().trim().max(2000).nullish(),
};

/** `fileNumber` is generated by the API and never accepted from a client. */
export const createPatientSchema = z.object(patientWritableFields);
export type CreatePatientInput = z.infer<typeof createPatientSchema>;

export const updatePatientSchema = z
  .object(patientWritableFields)
  .partial()
  .refine((input) => Object.keys(input).length > 0, 'At least one field must be provided');
export type UpdatePatientInput = z.infer<typeof updatePatientSchema>;

export const listPatientsQuerySchema = paginationQuerySchema.extend({
  /** Matches the file number, the name or the phone. */
  search: z.string().trim().min(1).max(120).optional(),
  gender: z.enum(GENDERS).optional(),
});
export type ListPatientsQuery = z.infer<typeof listPatientsQuerySchema>;
