-- Staff and clinic names, in both languages.
--
-- Generated by drizzle-kit as four `ADD COLUMN ... NOT NULL` and two
-- `DROP COLUMN`, which would have failed on any table holding rows and thrown
-- away the names it did not fail on. Widened by hand *before* it was applied
-- anywhere (CLAUDE.md forbids editing an applied migration, not writing one):
-- add nullable, carry the existing name into both languages, then constrain.
--
-- Every existing name therefore ends up in both columns. That is deliberate
-- and it is not a translation: it keeps every screen rendering exactly what it
-- rendered yesterday, and leaves the real Arabic spellings to be filled in
-- afterwards from the users screen. See the pull request note.

ALTER TABLE "clinics" ADD COLUMN "name_ar" text;--> statement-breakpoint
ALTER TABLE "clinics" ADD COLUMN "name_en" text;--> statement-breakpoint
UPDATE "clinics" SET "name_ar" = "name", "name_en" = "name";--> statement-breakpoint
ALTER TABLE "clinics" ALTER COLUMN "name_ar" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "clinics" ALTER COLUMN "name_en" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "users" ADD COLUMN "name_ar" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "name_en" text;--> statement-breakpoint
UPDATE "users" SET "name_ar" = "name", "name_en" = "name";--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "name_ar" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "name_en" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "clinics" DROP COLUMN "name";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "name";
