const AR = {
  common: {
    page: "صفحة {page} من {total}",
    printed: "تاريخ الطباعة",
  },

  receipt: {
    title: "إيصال قبض",
    number: "رقم الإيصال",
    date: "التاريخ",
    patient: "المريض",
    fileNumber: "رقم الملف",
    amount: "المبلغ المدفوع",
    reversedAmount: "المبلغ المسترد",
    method: "طريقة الدفع",
    note: "ملاحظات",
    balanceAfter: "الرصيد بعد الدفع",
    balanceAfterReversal: "الرصيد بعد الإلغاء",
    reversalTitle: "إيصال إلغاء",
    reversalOf: "إلغاء للإيصال رقم",
    signature: "توقيع المستلم",
    stamp: "ختم العيادة",
  },

  statement: {
    title: "كشف حساب",
    patient: "المريض",
    fileNumber: "رقم الملف",
    period: "الفترة",
    periodUntil: "حتى تاريخ",
    openingBalance: "رصيد أول المدة",
    closingBalance: "الرصيد المتبقي",
    totalCharges: "إجمالي المستحقات",
    totalPayments: "إجمالي المدفوعات",
    printedAt: "تاريخ الطباعة",
    all: "جميع الحركات حتى",
    columns: {
      date: "التاريخ",
      description: "البيان",
      charge: "المستحق",
      payment: "المدفوع",
      balance: "الرصيد",
    },
    payment: "دفعة",
    receipt: "إيصال قبض",
    reversal: "قيد إلغاء",
    reversedPayment: "إلغاء دفعة",
    empty: "لا توجد حركات خلال هذه الفترة",
  },

  labOrder: {
    title: "طلب عمل مخبري",
    number: "رقم الطلب",
    lab: "المختبر",
    date: "التاريخ",
    patient: "المريض",
    doctor: "الطبيب",
    workType: "نوع العمل",
    teeth: "الأسنان",
    material: "المادة",
    shade: "درجة اللون",
    expected: "موعد التسليم المتوقع",
    instructions: "التعليمات",
    signature: "توقيع المستلم",
  },

  labStatement: {
    title: "كشف حساب المختبر",
    lab: "المختبر",
    period: "الفترة",
    periodUntil: "حتى تاريخ",
    openingBalance: "رصيد أول المدة",
    closingBalance: "الرصيد المستحق للمختبر",
    printedAt: "تاريخ الطباعة",
    columns: {
      date: "التاريخ",
      description: "البيان",
      order: "المستحق",
      payment: "المدفوع",
      balance: "الرصيد",
    },
    reversal: "قيد إلغاء",
    empty: "لا توجد حركات خلال هذه الفترة",
  },

  treatmentPlan: {
    title: "خطة علاجية",
    patient: "المريض",
    fileNumber: "رقم الملف",
    printedAt: "تاريخ الطباعة",
    columns: {
      number: "#",
      procedure: "المعالجة",
      teeth: "الأسنان",
      status: "الحالة",
      price: "السعر التقديري",
    },
    statuses: { planned: "مخطّط", in_progress: "قيد التنفيذ" },
    total: "الإجمالي التقديري",
    disclaimer: "الأسعار تقديرية وقابلة للتعديل حسب ما تستدعيه الحالة أثناء المعالجة.",
    empty: "لا توجد معالجات مخطّطة",
    signatureDoctor: "توقيع الطبيب",
    signaturePatient: "توقيع المريض",
  },

  prescription: {
    title: "وصفة طبية",
    patient: "المريض",
    fileNumber: "رقم الملف",
    doctor: "الطبيب",
    date: "التاريخ",
    columns: {
      number: "#",
      drug: "الدواء",
      perDose: "الكمية في كل مرة",
      timesPerDay: "مرات في اليوم",
      duration: "المدة",
    },
    days: { one: "يوم واحد", two: "يومان", few: "{count} أيام", many: "{count} يوماً" },
    instructions: "التعليمات",
    notes: "ملاحظات",
    signatureDoctor: "توقيع الطبيب",
  },

  settlement: {
    title: "كشف تسوية طبيب زائر",
    doctor: "الطبيب",
    period: "الفترة",
    printedAt: "تاريخ الطباعة",
    columns: {
      date: "التاريخ",
      patient: "المريض",
      procedure: "المعالجة",
      amount: "المبلغ",
      materials: "المواد",
      clinicShare: "حصة العيادة",
      doctorShare: "حصة الطبيب",
    },
    totalRevenue: "إجمالي المبالغ",
    totalMaterials: "إجمالي المواد",
    totalClinicShare: "إجمالي حصة العيادة",
    totalDoctorShare: "إجمالي حصة الطبيب",
    paid: "المدفوع للطبيب",
    balance: "المتبقي للطبيب",
    empty: "لا توجد معالجات خلال هذه الفترة",
    signatureClinic: "توقيع العيادة",
    signatureDoctor: "توقيع الطبيب",
  },

  payroll: {
    title: "كشف الرواتب",
    month: "الشهر",
    printedAt: "تاريخ الطباعة",
    columns: {
      employee: "الموظف",
      salary: "الراتب الشهري",
      extras: "الإضافات",
      cuts: "الخصومات",
      due: "المستحق",
      paid: "المدفوع",
      remaining: "المتبقي",
    },
    totalDue: "إجمالي المستحق",
    totalPaid: "إجمالي المدفوع",
    totalRemaining: "إجمالي المتبقي",
    visitingShares: "حصص الأطباء الزائرين",
    staffCost: "تكلفة الموظفين",
    empty: "لا يوجد موظفون في هذا الشهر",
    signature: "توقيع الإدارة",
  },

  shoppingList: {
    title: "قائمة المشتريات",
    printedAt: "تاريخ الطباعة",
    note: "الكميات المقترحة تكفي للوصول إلى ضعف الحد الأدنى للمخزون، وهي إرشادية وليست إلزامية.",
    columns: {
      item: "المادة",
      unit: "الوحدة",
      current: "الكمية الحالية",
      minimum: "الحد الأدنى",
      suggested: "الكمية المقترحة",
      supplier: "المورّد",
    },
    empty: "لا توجد مواد دون الحد الأدنى للمخزون",
    signature: "توقيع المسؤول",
  },
};

const EN: typeof AR = {
  common: {
    page: "Page {page} of {total}",
    printed: "Printed",
  },
  receipt: {
    title: "Payment receipt",
    number: "Receipt no.",
    date: "Date",
    patient: "Patient",
    fileNumber: "File no.",
    amount: "Amount received",
    reversedAmount: "Amount returned",
    method: "Method",
    note: "Notes",
    balanceAfter: "Balance left after this payment",
    balanceAfterReversal: "Balance after this reversal",
    reversalTitle: "Reversal receipt",
    reversalOf: "Reverses receipt no.",
    signature: "Received by",
    stamp: "Clinic stamp",
  },
  statement: {
    title: "Account statement",
    patient: "Patient",
    fileNumber: "File no.",
    period: "Period",
    periodUntil: "Period to",
    openingBalance: "Opening balance",
    closingBalance: "Balance due",
    totalCharges: "Total charged",
    totalPayments: "Total paid",
    printedAt: "Printed",
    all: "All entries to",
    columns: {
      date: "Date",
      description: "Description",
      charge: "Charge",
      payment: "Payment",
      balance: "Balance",
    },
    payment: "Payment",
    receipt: "Receipt",
    reversal: "Reversal",
    reversedPayment: "Payment reversed",
    empty: "No entries in this period",
  },
  labOrder: {
    title: "Laboratory work order",
    number: "Order no.",
    lab: "Laboratory",
    date: "Date",
    patient: "Patient",
    doctor: "Doctor",
    workType: "Work",
    teeth: "Teeth",
    material: "Material",
    shade: "Shade",
    expected: "Expected",
    instructions: "Instructions",
    signature: "Received by",
  },
  labStatement: {
    title: "Laboratory statement",
    lab: "Laboratory",
    period: "Period",
    periodUntil: "Period to",
    openingBalance: "Opening balance",
    closingBalance: "Balance due to the laboratory",
    printedAt: "Printed",
    columns: {
      date: "Date",
      description: "Description",
      order: "Owed",
      payment: "Paid",
      balance: "Balance",
    },
    reversal: "Reversal",
    empty: "No entries in this period",
  },
  treatmentPlan: {
    title: "Treatment plan",
    patient: "Patient",
    fileNumber: "File number",
    printedAt: "Printed",
    columns: {
      number: "#",
      procedure: "Procedure",
      teeth: "Teeth",
      status: "Status",
      price: "Estimated price",
    },
    statuses: { planned: "Planned", in_progress: "In progress" },
    total: "Estimated total",
    disclaimer: "Prices are estimates and may change as treatment requires.",
    empty: "No planned treatments",
    signatureDoctor: "Doctor's signature",
    signaturePatient: "Patient's signature",
  },

  prescription: {
    title: "Prescription",
    patient: "Patient",
    fileNumber: "File number",
    doctor: "Doctor",
    date: "Date",
    columns: {
      number: "#",
      drug: "Medicine",
      perDose: "Amount each time",
      timesPerDay: "Times a day",
      duration: "Duration",
    },
    days: { one: "1 day", two: "2 days", few: "{count} days", many: "{count} days" },
    instructions: "Instructions",
    notes: "Notes",
    signatureDoctor: "Doctor's signature",
  },

  settlement: {
    title: "Visiting doctor settlement",
    doctor: "Doctor",
    period: "Period",
    printedAt: "Printed",
    columns: {
      date: "Date",
      patient: "Patient",
      procedure: "Procedure",
      amount: "Amount",
      materials: "Materials",
      clinicShare: "Clinic share",
      doctorShare: "Doctor share",
    },
    totalRevenue: "Total amount",
    totalMaterials: "Total materials",
    totalClinicShare: "Clinic share",
    totalDoctorShare: "Doctor share",
    paid: "Paid to the doctor",
    balance: "Owed to the doctor",
    empty: "No treatments in this period",
    signatureClinic: "Clinic signature",
    signatureDoctor: "Doctor signature",
  },

  payroll: {
    title: "Payroll",
    month: "Month",
    printedAt: "Printed",
    columns: {
      employee: "Employee",
      salary: "Monthly salary",
      extras: "Extras",
      cuts: "Cuts",
      due: "Due",
      paid: "Paid",
      remaining: "Remaining",
    },
    totalDue: "Total due",
    totalPaid: "Total paid",
    totalRemaining: "Total remaining",
    visitingShares: "Visiting doctor shares",
    staffCost: "Staff cost",
    empty: "No employees this month",
    signature: "Management signature",
  },

  shoppingList: {
    title: "Shopping list",
    printedAt: "Printed",
    note: "Suggested quantities reach twice the minimum — a guide, not an order.",
    columns: {
      item: "Item",
      unit: "Unit",
      current: "In stock",
      minimum: "Minimum",
      suggested: "Suggested",
      supplier: "Supplier",
    },
    empty: "Nothing below its minimum",
    signature: "Signature",
  },
};

export type DocumentLanguage = "ar" | "en";

export type DocumentStrings = typeof AR;

export const documentStrings = (language: DocumentLanguage): DocumentStrings =>
  language === "en" ? EN : AR;

export const documentDirection = (language: DocumentLanguage): "rtl" | "ltr" =>
  language === "en" ? "ltr" : "rtl";
