import {
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUSES,
  NOTIFICATION_TEMPLATES,
} from '@clinic/shared';
import { index, integer, jsonb, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

import { appointments } from '@api/database/schema/appointments';
import { clinics } from '@api/database/schema/core';
import { patients } from '@api/database/schema/patients';

export const notificationChannelEnum = pgEnum('notification_channel', NOTIFICATION_CHANNELS);
export const notificationTemplateEnum = pgEnum('notification_template', NOTIFICATION_TEMPLATES);
export const notificationStatusEnum = pgEnum('notification_status', NOTIFICATION_STATUSES);

/**
 * Every message the clinic tried to send.
 *
 * Append-only and never soft-deleted, like the ledgers: a message that failed
 * is a row saying so, not an absence. It is written **before** the provider is
 * called, so a provider that throws or hangs still leaves a trace — a send that
 * vanishes without a record is the one failure a notification log exists to
 * prevent.
 *
 * It is also the dedupe key for reminders. There is no separate "sent markers"
 * table because this *is* that table: "has the 24h reminder for appointment X
 * gone out?" is a lookup on `(appointment_id, template)`, and a second table
 * holding the same fact could disagree with this one.
 */
export const notificationsLog = pgTable(
  'notifications_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clinicId: uuid('clinic_id')
      .notNull()
      .references(() => clinics.id),
    /** Destination, as dialled. Not joined to a patient: a message can go to
     *  a number that has no record yet, which is exactly the booking case. */
    to: text('to').notNull(),
    channel: notificationChannelEnum('channel').notNull(),
    template: notificationTemplateEnum('template').notNull(),
    /** The interpolation values, so a sent message can be reconstructed. */
    vars: jsonb('vars').$type<Record<string, string>>().notNull().default({}),
    status: notificationStatusEnum('status').notNull().default('queued'),
    error: text('error'),
    appointmentId: uuid('appointment_id').references(() => appointments.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('notifications_log_clinic_created_idx').on(table.clinicId, table.createdAt),
    /** The reminder scheduler's own index: one lookup per candidate. */
    index('notifications_log_appointment_idx').on(table.appointmentId, table.template),
  ],
);

/**
 * A one-time code for a booking made on the public page.
 *
 * The code is **hashed**, never stored in the clear: this table is read by
 * anyone with database access, and a plaintext column would let them confirm
 * bookings they did not make. It is a SHA-256 digest rather than argon2 for the
 * same reason the refresh tokens are — the value is generated by a CSPRNG, so
 * there is nothing to brute-force offline that the three-attempt limit does not
 * already stop online.
 *
 * One row per booking, replaced on resend. Rows are hard-deleted by the
 * housekeeping job once spent: this is operational data, not a medical or
 * financial record, and keeping a used code has no value.
 */
export const bookingOtps = pgTable(
  'booking_otps',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    clinicId: uuid('clinic_id')
      .notNull()
      .references(() => clinics.id),
    appointmentId: uuid('appointment_id')
      .notNull()
      .references(() => appointments.id),
    patientId: uuid('patient_id')
      .notNull()
      .references(() => patients.id),
    /** SHA-256 of the six digits. */
    codeHash: text('code_hash').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /** Wrong guesses so far. Three is the limit; the row is then dead. */
    attempts: integer('attempts').notNull().default(0),
    consumedAt: timestamp('consumed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('booking_otps_appointment_idx').on(table.appointmentId)],
);
